### ISSUE TITLE
Suggestion: switch to Expose from PHP IDS

### ISSUE THREAD

**Issue by InvisibleKind** [DMKEBUSINESSGMBH/typo3-mkphpids#2]
The PHP IDS projects looks like being abandoned, but there is a follower, based on it's roots: [Expose](https://github.com/enygma/expose), which is actively maintained.

Makes sense?

**Comment by hannesbochmann** [comment]
We will take a look into Expose. Thanks for the hint.

**Comment by hannesbochmann** [comment]
I see one problem: Expose calculates in most cases a lower impact on attacks. So current installations of mkphpids wouldn't be backwards compatible as the configuration wouldn't produce the same results. 
Furthermore I think the benefits of switching are not that big. PHPIDS is still a good choice even though there seems to be no further development (the current attack patterns don't change that often and are therefore still good to use).
That's why we wont switch to Expose at the moment, but thanks for the hint again.
